version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
#  aws-ecs: circleci/aws-ecs@0.0.10
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION
          repo: gql-auth
          tag: 'latest'
          skip-when-tags-exist: false
          filters:
            branches:
              only:
                - master
#      - aws-ecs/deploy-service-update:
#          requires:
#            - aws-ecr/build-and-push-image
#          family: 'gql-auth-service'
#          cluster-name: 'gql-cluster'
#          container-image-name-updates: 'container=gql-auth-container,tag=latest'
